version: '3'
services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=decode
      - POSTGRES_DB=postgres
      - DATABASES=iotstore,iotencoder,policystore

  datastore:
    image: thingful/iotstore-amd64:v0.3.1
    ports:
      - "8080:8080"
    environment:
      - IOTSTORE_DATABASE_URL=postgres://decode:password@postgres:5432/iotstore?sslmode=disable
    depends_on:
      - postgres
    command: [ "server" ]

  policystore:
    image: thingful/policystore-amd64:v0.0.6
    ports:
      - "8082:8082"
    environment:
      - POLICYSTORE_DATABASE_URL=postgres://decode:password@postgres:5432/policystore?sslmode=disable
      - POLICYSTORE_ENCRYPTION_PASSWORD=Sf5WUu1cF3Xovc8uVmjkUg==
      - POLICYSTORE_HASHID_SALT=iUe5l1NGT85p7MHPAyaXIA==
    depends_on:
      - postgres
    command: [ "server", "--verbose" ]

  encoder:
    image: thingful/iotenc-amd64:v0.1.0
    ports:
      - "8081:8081"
    environment:
      - IOTENCODER_DATABASE_URL=postgres://decode:password@postgres:5432/iotencoder?sslmode=disable
      - IOTENCODER_ENCRYPTION_PASSWORD=UZicimoFtGAzjGtC65gZcA==
      - IOTENCODER_HASHID_SALT=9iLI2qRrwc5FOIZKuKOHhg==
      - IOTENCODER_REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    command: [ "server", "--verbose", "--datastore", "http://datastore:8080" ]

  broker:
    image: thingful/scfake:v0.0.3
    ports:
      - "1883"
      - "8083:8080"
    environment:
      - HTTP_PORT=8080

  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:5.1.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - grafana_vol:/var/lib/grafana
    depends_on:
      - prometheus

  redis:
    image: redis:5-alpine

  webdemo:
    image: thingful/decode-demo:v0.0.3
    ports:
      - "5000:5000"
    environment:
      - DATASTORE_BASE=http://datastore:8080/twirp/decode.iot.datastore.Datastore/
      - ENCODER_URL=http://encoder:8081/twirp/decode.iot.encoder.Encoder/
    depends_on:
      - postgres
      - broker
      - datastore

volumes:
  postgres_vol:
  grafana_vol:
