version: '3'
services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=decode
      - POSTGRES_DB=postgres
      - DATABASES=iotstore

  datastore:
    image: thingful/iotstore-amd64:v0.0.2
    ports:
      - "8080"
    restart: always
    environment:
      - IOTSTORE_DATABASE_URL=postgres://decode:password@postgres:5432/iotstore?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - ./docker:/docker
    entrypoint: /docker/entrypoint.sh
    command: [ "/iotstore", "server" ]

volumes:
  postgres_vol:
